name: Build and push Docker image

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      image_version_full: ${{ steps.docker_image_version.outputs.fullVersion }}
      image_version_major: ${{ steps.docker_image_version.outputs.majorVersion }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: ${{ github.ref_name }}
          patchList: 'fix, bugfix, perf, refactor, test, tests, chore'

      - name: Create Docker image version
        id: docker_image_version
        run: |
          fullVersion="${{ steps.semver.outputs.nextStrict }}"
          majorVersion="${{ steps.semver.outputs.nextMajorStrict }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "fullVersion=$fullVersion" >> "$GITHUB_OUTPUT"
            echo "majorVersion=$majorVersion" >> "$GITHUB_OUTPUT"
          else
            echo "fullVersion=${fullVersion}-beta" >> "$GITHUB_OUTPUT"
            echo "majorVersion=${majorVersion}-beta" >> "$GITHUB_OUTPUT"
          fi

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.semver.outputs.next }}',
              sha: context.sha
            })

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: ${{ github.ref_name }}
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          draft: ${{ github.ref != 'refs/heads/main' }}
          makeLatest: ${{ github.ref == 'refs/heads/main' }}
          name: ${{ steps.semver.outputs.next }}
          body: ${{ steps.changelog.outputs.changes }}
          tag: ${{ steps.semver.outputs.next }}
          commit: ${{ github.sha }}
          token: ${{ github.token }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: create-release

    steps:
      - name: Show selected ref
        run: |
          echo "Ref:  $GITHUB_REF"
          echo "SHA:  $GITHUB_SHA"
          echo "Repo: $GITHUB_REPOSITORY"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ needs.create-release.outputs.image_version_full }}
            type=raw,value=${{ needs.create-release.outputs.image_version_major }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }} # TODO: Check if this makes sense
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}